CREATE TABLE IF NOT EXISTS Patrons (PatronID INTEGER PRIMARY KEY AUTOINCREMENT, PatronName TEXT NOT NULL, ContactNumber TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Employees (EmployeeID INTEGER PRIMARY KEY AUTOINCREMENT, StaffName TEXT NOT NULL, StaffPin TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Brands(BrandID INTEGER PRIMARY KEY AUTOINCREMENT, BrandName TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Tools (ToolID INTEGER PRIMARY KEY AUTOINCREMENT, BrandID INTEGER NOT NULL, ToolType TEXT NOT NULL, Comment TEXT NOT NULL, Active NUMERIC NOT NULL, FOREIGN KEY(BrandID) REFERENCES Brands(BrandID));
CREATE TABLE IF NOT EXISTS Loans (LoanID INTEGER PRIMARY KEY AUTOINCREMENT, PatronID INTEGER NOT NULL, ToolID INTEGER NOT NULL, EmployeeID INTEGER NOT NULL, WorkStation TEXT NOT NULL,
DateLoaned DATETIME NOT NULL,DateReturn DATETIME, FOREIGN KEY(PatronID) REFERENCES Patrons(PatronID), FOREIGN KEY(ToolID) REFERENCES Tools(ToolID), FOREIGN KEY(EmployeeID) 
REFERENCES Employees(EmployeeID));
